image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - johnpapa.Angular2@9.1.2:uM4PeIXJe98IILNHmOn+nA==
    - eamodio.gitlens@10.2.1:WIWu3zHU4VPT8r/v866LUw==
    - mhutchie.git-graph@1.24.0:1YXb3C/Q2X3rk146GJk9WA==